-- ============================================================
--  ⚠️  Ce fichier n'est plus la source de vérité.
--
--  Le schéma est désormais géré par des MIGRATIONS versionnées,
--  dans  supabase/migrations/  , appliquées avec :
--
--      supabase db push        # pousse les migrations vers le cloud
--      npm run db:push         # (raccourci équivalent)
--
--  Pour une nouvelle modification de la base :
--      supabase migration new <nom>   # crée un fichier SQL horodaté
--      # …édite-le…
--      supabase db push               # applique
--
--  Le schéma initial complet se trouve dans :
--      supabase/migrations/20260612115027_init_schema.sql
-- ============================================================
